# Sesi Warna Utama
background            #121212
foreground            #e0e0e0
cursor                #ffffff
selection_background  #2d2d2d
selection_foreground  #ffffff

# Palet Warna Terminal (Monochrome)
# Black & Grey
color0  #1c1c1c
color8  #4e4e4e

# Red (Dibuat agak abu-abu gelap)
color1  #585858
color9  #626262

# Green (Abu-abu terang)
color2  #b0b0b0
color10 #c6c6c6

# Yellow
color3  #8a8a8a
color11 #a8a8a8

# Blue
color4  #9e9e9e
color12 #bcbcbc

# Magenta / Purple (Warna yang tadi bikin bermasalah)
color5  #767676
color13 #e4e4e4

# Cyan
color6  #808080
color14 #d0d0d0

# White
color7  #e0e0e0
color15 #ffffff
