format = """
[░▒▓](#3b4252)\
$os\
$username\
[](bg:#4c566a fg:#3b4252)\
$directory\
[](fg:#4c566a bg:#434c5e)\
$git_branch\
$git_status\
[](fg:#434c5e bg:#2e3440)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#2e3440 bg:#d8dee9)\
$time\
[ ](fg:#d8dee9)\
$line_break$character"""

[os]
disabled = false
style = "bg:#3b4252 fg:#e5e9f0"

[os.symbols]
Arch = "󰣇 "

[username]
show_always = true
style_user = "bg:#3b4252 fg:#e5e9f0"
style_root = "bg:#3b4252 fg:#bf616a"
format = '[$user]($style)'

[directory]
style = "bg:#4c566a fg:#e5e9f0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "bg:#434c5e fg:#e5e9f0"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#434c5e fg:#e5e9f0"
format = '[$all_status$ahead_behind ]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:#d8dee9 fg:#2e3440"
format = '[  $time ]($style)'

[character]
disabled = false
success_symbol = '[❯](bold #e5e9f0)'
error_symbol = '[❯](bold #bf616a)'
