# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #CECECE
background         #000000
cursor             #8E8E8E

active_tab_foreground     #000000
active_tab_background     #CECECE
inactive_tab_foreground   #CECECE
inactive_tab_background   #000000

active_border_color   #CECECE
inactive_border_color #000000
bell_border_color     #333333

color0      #000000
color1		#333333
color2		#3A3A3A
color3		#414141
color4		#484848
color5		#4F4F4F
color6		#565656
color7		#B0B1B1
color8		#7C7C7C
color9		#434443
color10		#4D4D4D
color11		#565656
color12		#606060
color13		#696A6A
color14		#737373
color15		#B0B1B1
